DELIMITER $$

CREATE FUNCTION FN_GET_CIRCLE_AREA(radius FLOAT)
RETURNS FLOAT
DETERMINISTIC
NO SQL
BEGIN
  DECLARE area FLOAT;
  SET area = PI() * radius * radius;
  RETURN area;
END$$

DELIMITER ;
SELECT FN_GET_CIRCLE_AREA(10);
