# 01. 請列出薪資比所有SALESMAN還低的員工
SELECT ENAME, SAL
FROM EMP
WHERE SAL < ALL (
    SELECT SAL FROM EMP WHERE JOB = 'SALESMAN'
);


# 02. 請列出到職年(到職日之年)最早的兩年，那兩年到職的員工，並依到職日排序
SELECT ENAME, JOB, HIREDATE, YEAR(HIREDATE) AS HIRE_YEAR
FROM EMP
WHERE YEAR(HIREDATE) IN (
    SELECT DISTINCT YEAR(HIREDATE)
    FROM EMP
    ORDER BY YEAR(HIREDATE)
    LIMIT 2
)
ORDER BY HIREDATE;


# 03. 請列出主管的主管是KING 的員工
SELECT E.ENAME
FROM EMP E
WHERE E.MGR IN (
    SELECT M.EMPNO
    FROM EMP M
    WHERE M.MGR = (
        SELECT EMPNO FROM EMP WHERE ENAME = 'KING'
    )
);


# 04. 請列出部門內，員工薪資剛好有3種薪資等級之部門名稱、部門所在地
SELECT D.DNAME, D.LOC
FROM DEPT D
JOIN EMP E ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME, D.LOC
HAVING COUNT(DISTINCT E.SAL) = 3;


# 05. 請列出跟員工姓名最後一字元是S的員工同部門，該部門薪資最低的員工之部門名稱、姓名、薪資
SELECT D.DNAME, E1.ENAME, E1.SAL
FROM EMP E1
JOIN DEPT D ON E1.DEPTNO = D.DEPTNO
WHERE (E1.DEPTNO) IN (
    SELECT DISTINCT DEPTNO
    FROM EMP
    WHERE ENAME LIKE '%S'
)
AND E1.SAL = (
    SELECT MIN(SAL)
    FROM EMP E2
    WHERE E2.DEPTNO = E1.DEPTNO
);

