# 01. 請列出公司一年需發出薪資總和 (不含獎金)
SELECT SUM(SAL) * 12 AS YEAR_TOTAL_SALARY 
FROM EMP;


# 02. 請列出公司平均月薪
SELECT AVG(SAL) AS AVERAGE_MONTHLY_SALARY 
FROM EMP;


# 03. 請列出各部門編號、部門每月發出薪資總和，並依部門編號遞增排序
SELECT DEPTNO, SUM(SAL) AS MONTHLY_TOTAL_SALARY 
FROM EMP 
GROUP BY DEPTNO 
ORDER BY DEPTNO ASC;


# 04. 請列出職稱、職稱平均薪資、職稱人數
SELECT JOB, AVG(SAL) AS AVERAGE_SALARY, COUNT(*) AS EMPLOYEE_COUNT 
FROM EMP 
GROUP BY JOB;


# 05. 請列出部門編號、部門最低薪資、部門最高薪資
SELECT DEPTNO, MIN(SAL) AS MIN_SALARY, MAX(SAL) AS MAX_SALARY 
FROM EMP 
GROUP BY DEPTNO;


# 06. 請列出到職年、該年到職人數
SELECT YEAR(HIREDATE) AS HIRE_YEAR, COUNT(*) AS EMPLOYEE_COUNT 
FROM EMP 
GROUP BY YEAR(HIREDATE) 
ORDER BY HIRE_YEAR;

