# 01. 請新建一個View，名為V_DEPT_ECOUNT，列出部門編號、部門人數

CREATE VIEW V_DEPT_ECOUNT AS
SELECT DEPTNO, COUNT(*) AS EMP_COUNT
FROM EMP
GROUP BY DEPTNO;


# 02. 請新建一個View，名為V_DEPT_ECOUNT2，基底資料表為第01題建立的檢視表V_DEPT_ECOUNT，並將欄位依序命名為DEPARTMENT_NO、EMPLOYEE_COUNT

CREATE VIEW V_DEPT_ECOUNT2 AS
SELECT DEPTNO AS DEPARTMENT_NO, EMP_COUNT AS EMPLOYEE_COUNT
FROM V_DEPT_ECOUNT;


# 03. 請撰寫一select敘述，用第02題建立的檢視表V_DEPT_ECOUNT2，join資料表DEPT，列出部門名稱、部門人數

SELECT D.DNAME AS DEPARTMENT_NAME, V.EMPLOYEE_COUNT
FROM DEPT D
JOIN V_DEPT_ECOUNT2 V ON D.DEPTNO = V.DEPARTMENT_NO;


# 04. 請新建一個View，名為V_EMP10，其內含有部門編號10的所有員工資料，並加上with check option限制DML

CREATE VIEW V_EMP10 AS
SELECT *
FROM EMP
WHERE DEPTNO = 10
WITH CHECK OPTION;


# 05. 請修改檢視表V_DEPT_ECOUNT2，將欄位命名依序改為DEPT_NO、EMP_COUNT，其餘部分不變

DROP VIEW IF EXISTS V_DEPT_ECOUNT2;

CREATE VIEW V_DEPT_ECOUNT2 AS
SELECT DEPTNO AS DEPT_NO, EMP_COUNT AS EMP_COUNT
FROM V_DEPT_ECOUNT;


# 06. 請移除檢視表V_DEPT_ECOUNT2

DROP VIEW IF EXISTS V_DEPT_ECOUNT2;

