# 01. 請列出所有員工的員工編號、姓名、職稱、部門編號及部門名稱
SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO;


# 02. 請列出所有部門編號為30 且 職稱為"SALESMAN"之部門名稱、員工姓名、獎金
SELECT D.DNAME, E.ENAME, E.COMM
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO = 30 AND E.JOB = 'SALESMAN';


# 03. 請列出薪水等級為"B"的員工之員工編號、員工姓名、薪資
SELECT E.EMPNO, E.ENAME, E.SAL
FROM EMP E
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE S.GRADE = 'B';


# 04. 請列出部門編號、部門名稱及部門人數
SELECT D.DEPTNO, D.DNAME, COUNT(E.EMPNO) AS EMP_COUNT
FROM DEPT D
LEFT JOIN EMP E ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;


# 05. 請列出每個主管之姓名、直屬下屬人數、直屬下屬平均薪資，並依 直屬下屬人數遞減、主管姓名遞增 排序
SELECT M.ENAME AS MANAGER_NAME,
       COUNT(E.EMPNO) AS SUBORDINATE_COUNT,
       AVG(E.SAL) AS AVG_SUB_SALARY
FROM EMP E
JOIN EMP M ON E.MGR = M.EMPNO
GROUP BY M.ENAME
ORDER BY SUBORDINATE_COUNT DESC, MANAGER_NAME ASC;

